### PR TITLE
Organized machines in alphabetic order by reciepe.

### PR DESCRIPTION
**Pull request by FairfieldTekLLC**
This the change I wrote about in the issue.  I just finished testing it.  Makes it easier to find the machine making what you are looking for.

### CODE REVIEW

**Comment by thoda-dev** [comment]
Sorry, but this is not how the HUD is working and i do not want to change the default sorting system, currently it's sorted by machine name, and it's permitting to sort any machine just by renaming it, doesn't matter the order you really want.

Eg: if you want to sort machines by production lines and not by receipe, you can do it by added something in the name, and i don't want to change that in the actual system.

Also, by sorting it by receipe, that means you must query all the machine before you load the view, that could be a problem on really huge industries (this was done before and i changed it to pull only the status from machines displayed in the view)

For your information, i'm currently working on a full rewrite of the script with several new things included like a group system that permit to display machines by groups and not by types like actually, a sorting by machines status is also in progress and all theses sorting are optionnal. There is also a version for screens and a full rewrite of the display in HUD mode.

**Comment by FairfieldTekLLC** [comment]
Oh, ok.  I just really like your project and I think you did an amazing job with it.  I respect the direction you are going and the effort you put into it.  I was just trying to offer some help.  Thank you for your effort, I know it is not easy managing a system like that.

Take care,

Vince Gee
FairfieldTek L.L.C.
***@***.***

**Comment by thoda-dev** [comment]
I apreciate the help but i want to it correspond for the most of people and force sorting in a way or another is not so good for that.
You can still keep that code for your use case, that's the reason i openned the source.

**Comment by FairfieldTekLLC** [comment]
If you need testing on your new stuff, let me know and I will set up test environments for you in game.  If you need someone to look over your shoulder to help solve something let me know.  I’d be more than happy to help.  I’ve been programming 25 years now and I am pretty good at spotting mistakes and such.

Vince Gee
FairfieldTek L.L.C.
***@***.***

**Comment by thoda-dev** [comment]
Join the guilded server, there is a self assignable role to test the alpha version.
Note that is is not yet available for alpha but it should be during march

**Comment by FairfieldTekLLC** [comment]
Will do.

Vince Gee
FairfieldTek L.L.C.
***@***.***

**Comment by FairfieldTekLLC** [comment]
Can’t connect to your server.

***@***.***

Vince Gee
FairfieldTek L.L.C.
***@***.***

**Comment by thoda-dev** [comment]
https://guilded.jericho.dev

**Pull request closed without merging**
